feat: Support for Servlet API 6+ (#250)
* feat: Improve diagnostics message on NoClassDefFoundError during discovery

* deps: Use fine-grained Jakarta EE dependencies instead of jakartaee-web-api

* feat: Split module for Servlet API 5 support

* feat: Split module for Servlet API 6 support